### ISSUE TITLE
Merge i-Trees species with our species data...

### ISSUE THREAD

**Issue by MarkCDAshdown** [KitWallace/treemap#123]
and map their US Common names with our Common names

**Comment by KitWallace** [comment]
In general I don't want to include species which are not represented in our collection since it will just slow things down.  I have thought of adding some species which are seen elsewhere (for example are in Paul Wood's London Street Trees so we could get a list of missing trees,  

Re Common names, my comparison shows that we have most of these amongst our multiple common name already and the missng ones are usually American - eg Sycamore Maple for Sycamore
