### ISSUE TITLE
latin name errors

### ISSUE THREAD

**Issue by KitWallace** [KitWallace/treemap#6]
Aesculs flava  to Aesculus flava
Aesculus turbinate to Aesculus turbinata
Betula ermani to Betula ermanii
73,74 Black Moris negra  - missing comma  and sb Morus nigra
Catalpa bignoniodes to Catalpa bignonioides 
Cedrus deodora sb Cedrus deodara
Cercidifolium japonicum to cercidiphyllum japonicum
Lawson's Cypress to Lawson Cypress
Chinese Ehretia  = probably Ehretia acuminata  common name Koda
86 missing comma
56 , 57 missing comma
193 missing comma
107 Crypotomeria japonica to Cryptomeria japonica
96 Paulonia tomentosa to Paulownia tomentosa
3 Cupressus Macrocarpa  to Cupressus macrocarpa
98 Eucalyptus gunii to Eucalyptus gunnii

**Comment by MarkCDAshdown** [comment]
OK, all changes now applied. MCDA

**Comment by MarkCDAshdown** [comment]
[Bristol tree champions text.docx](https://github.com/KitWallace/treemap/files/510493/Bristol.tree.champions.text.docx)

and the latest Word version for completeness

**Comment by MarkCDAshdown** [comment]
[champions database2.xlsx](https://github.com/KitWallace/treemap/files/510505/champions.database2.xlsx)

Here are some comments from David Bland and the file he refers to. not sure I follow him. Do you?

"Mark
I see the problem, but the mapping exercise does not work because I have used the name of a tree in more than one way. The resulting map shows every usage of the word, say Sycamore, but actually shows trees other than sycamore because I am making comparisons. 
For the majority of species there should be a single map point because I mention just the oldest specimen. For a species like Oak where there are a number of trees over the five metre circumference this will not be true.
The point of the excel sheet is to make it easy to find the important trees in, say, St Andrews park. 
I am not sure how to achieve that! I attach the excel spread sheet  with grid refs, and sorted it by species. That, rather than the word text should be the source for the maps. Will this work?
Oh, and yes, the word champion is now being used in too many senses-  your proposal, and the re-ordering of the names is very helpful. As for photos, I will dig out what I can. I did not automatically photo the tree smentioned as I would now. I will see what I can find.
Richard"

**Comment by KitWallace** [comment]
Ok latest version installed - still some editing to do .

I dont know what he means either  - I agree it would be nice to get the
site included - markup in the text perhaps - but otherwise the text is much
richer than the spreadsheet (although there are slighly more  trees)

 ps Im still not handling the entries with multiple numbers

**Comment by KitWallace** [comment]
I think it may be about the handling of the multiple entries - just
repeating the text doesnt look right eg.
http://kitwallace.co.uk/trees/treehtml.xq?common=Ash,%20Common
bit of redesign needed here  I think
ps Ive added girth and sorted to descending girth on common name lists -
looking at expanding this list when there are only a few - is that what you
were suggesting?

**Comment by MarkCDAshdown** [comment]
How about this for a solution:
"15. Cedar of Lebanon, Cedrus Libani. ST5600 7640. Stoke Lodge. Girth 605cm. Age 150 years. There are three Cedars in the Stoke Lodge grounds all the same size and Age, though one unfortunately is dead, and being sculpted. There are probably more Lebanon Cedars in Britain than in the state of Lebanon. **_Includes trees 15 & 17_**.

18. Common Oak, Quercus robur. ST 5400 7738. Kings Weston estate. Girth 600cm. Age 450 years. This is the oldest tree in the Kings Weston estate, and predates the house. It is on a steep bank running down to a path, and is very tall and vigorous. It is surprisingly difficult to find given its huge bulk.

19. London Plane, Platanus x hispanica. ST5410 7779. Kings Weston Lane. Girth 600cm. Age 200 years. There are three giant planes in a tiny strip of woodland off Kings Weston lane. Until five years ago they were towering trees, but fears that they might collapse and cause damage, led to all three being cut down to about twenty feet in height. Their vast girth is unaltered, and all three are putting out new shoots. Whereas once they dominated, now they have to be looked for. **_Includes trees 20 & 21_**."

Here's the new .txt ver - [Bristol tree champions.txt](https://github.com/KitWallace/treemap/files/510625/Bristol.tree.champions.txt)

I will put the preamble on the main page, but i think we need some way to relate the tress to his three sections, A, B & C. Any thoughts?

**Comment by MarkCDAshdown** [comment]
sorry - just saw the typo! Doh! this is the latest ver - [Bristol tree champions.txt](https://github.com/KitWallace/treemap/files/510635/Bristol.tree.champions.txt)

**Comment by MarkCDAshdown** [comment]
latest verion - more typos - [Bristol tree champions.txt](https://github.com/KitWallace/treemap/files/510972/Bristol.tree.champions.txt)

**Comment by KitWallace** [comment]
Uploaded - still a few punctuation errors, looking at the list of common
names and latin names

Decided I cant fit the shower since the pipework needs some copperwork so
I've booked your John to come next week.

C

**Comment by KitWallace** [comment]
These errors now fixed

**Comment by MarkCDAshdown** [comment]
Sorry about the shower :(

more punctuation errors - shite! send me a list of any you find
I have gone ahead and published these new pages on the web site - bristoltreeforum.org

**Comment by KitWallace** [comment]
Yes I just found that when I was browsing the new site!

Looking to add the sections (as a tag on each entry)  - I can use the
ranges although the added letter suffix makes that a bit messier -  .1, .2
would be better for me ;)

**Comment by MarkCDAshdown** [comment]
'The location of all trees can be downloaded as kml for viewing in Google Earth' - nothing gets downloaded - just shows the .xml.

and can we have each acknowledgement and guidance on a separate line - makes it easier to read.

'Looking to add the sections (as a tag on each entry) ' you mean 'Section 1' etc. rather than A, B C? sure.

**Comment by MarkCDAshdown** [comment]
Sorry I mean each acknowledgement and guidance _each_ on a separate line

**Comment by KitWallace** [comment]
I mean the letter suffixes which were added to numbers 88, 88a  I see there
are a lot now so I guess I can work around it.

**Comment by MarkCDAshdown** [comment]
i see. so you want 88.1 rather than 88a?
